composer.json, src/AbstractDaemonApplication.php, src/AbstractWebApplication.php
This PR removes the hard dependency to the Session, String, and URI packages as these are only dependencies of the web application class; the CLI and base classes do not require these packages to function.
Updated references to `$this->session` in the web application class to call `getSession()` instead and have the method throw an exception if the Session object has not been set.
=> Miscellaneous updates

src/AbstractDaemonApplication.php
Changes the daemon application class to not access the configuration directly by the parent class member var but instead uses the public API.
=> Don't directly access config

src/AbstractWebApplication.php
Fixes a couple of instances missed in #44
=> Use Input to retrieve $_SERVER information

Tests/AbstractApplicationTest.php, Tests/AbstractCliApplicationTest.php, Tests/AbstractWebApplicationTest.php, src/AbstractCliApplication.php, src/AbstractWebApplication.php
Restructure's `AbstractApplicationTest`, `AbstractCliApplicationTest`, and `AbstractWebApplicationTest` to use the PHPUnit API for mocking objects (concrete and abstract) and our own API for injecting objects versus using our Reflection based TestHelper to manipulate the class variables.  Also uses PHPUnit's assertions to test the objects as appropriate and deal with instances where we need to adjust values in superglobals.
=> Restructure application class tests

Tests/AbstractWebApplicationTest.php, src/AbstractWebApplication.php
As per comment, 'status' headers need to be handled slightly differently, but the code was adding a new 'status' header field rather than altering the HTTP response code.
=> HTTP status response not rendered correctly

Tests/AbstractWebApplicationTest.php, Tests/Web/Stubs/JWebClientInspector.php, src/AbstractWebApplication.php
This PR fixes the method names to comply with the CamelCase rules mentioned here:
http://joomla.github.io/coding-standards/?coding-standards/chapters/php.md
> ...be written in CamelCase even if using traditionally uppercase acronyms (such as XML, HTML).
Not touching casing of class names as this requires changes in casing in file names and causes issues at this point.
=> [codestyle] Fixed first letter casing in method names

README.md
Corrected the 401 header set in the Web Application ::setHeader() example.
=> Minor typo in examples in README.md

src/Web/WebClient.php
For full user agent string: `Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; LCJB; rv:11.0) like Gecko`
LCJB is in this case an OEM identifier, as described here: [https://user-agents.me/windows-oem-manufacturer-list](https://user-agents.me/windows-oem-manufacturer-list)
=> Include IE11 using OEM indentifier

src/AbstractCliApplication.php, src/Cli/CliInput.php
Why?
I'm working on a console app, which uses commands as separate classes, very similar to these in [framework-status](https://github.com/mbabker/framework-status/tree/master/cli/Command) repository.
I'd like commands to have a possibility to be executed outside the `AbstractCliApplication`, anyway in my opinion commands don't not necessarily need access to whole application object. Usually it's just output, input and some objects from container.
At this moment the CLI application [input is a method](https://github.com/joomla-framework/application/blob/master/src/AbstractCliApplication.php#L103), moving into new class allows to pass it along or use own one with predefined batch of inputs.
Maybe even good for testing, but I'm not there yet.
=> Moving the Cli input into new class

Tests/Web/WebClientTest.php, src/Web/WebClient.php
Partial Pull Request for Issue #59 
- Adds Blink engine to webclient
- Fixes Blink vs webkit
- Adds tests to verify chrome with blink vs chrome with webkit is detected correctly
- Adds some more common bots to the bots test to verify detection of those common bots
Review Travis tests
none
=> Add Blink engine to webclient

src/AbstractDaemonApplication.php
The daemon application class has never really fit in well with the Joomla API.  Additionally [most of the class has no test coverage](https://framework.joomla.org/coverage/application/AbstractDaemonApplication.php.html) and we don't really know if the class is even working at this point (it went through a round of refactoring when transitioning from Platform to Framework but to my knowledge the changes were never validated through real use or tests).  As the class is a mild black hole, I'd like to suggest deprecating it.
N/A
Note the deprecation
=> Deprecate the daemon application

Tests/AbstractWebApplicationTest.php, composer.json, docs/index.md, docs/v1-to-v2-update.md, src/AbstractWebApplication.php, src/Exception/UnableToWriteBody.php
This adds PSR-7 compatible responses to our Application layer.
There is one b/c breaking change - getBody no longer accepts toArray as a parameter as it stored in a stream object now rather than as an array of strings
=> Add PSR-7 compatible responses

Tests/AbstractWebApplicationTest.php, Tests/Stubs/ConcreteWeb.php, src/AbstractWebApplication.php
Generating a form token is application specific. So let's make this method abstract and stop trying to come up with dozens of framework specific ways to build a session token.
If people are happy with this then I'll add it to the docs
=> Make getFormToken an abstract method

src/AbstractWebApplication.php
Allow devs who set a full `Psr\Http\Message\ResponseInterface` object to the application to set the `Content-Type` header within the object as well as the `Last-Modified` and `Expires` headers when the application is set to allow cached responses.  If the headers are already set in the response object, we won't overwrite these values when sending the response, otherwise it should be business as usual.
I purposely didn't touch the no caching route as that is setting some sensible default values for now.
=> Allow Content-Type, Last-Modified, and Expires headers to be set in the Response object

Tests/Stubs/ConcreteDaemon.php, src/AbstractDaemonApplication.php, src/AbstractWebApplication.php
Use `@link` over `@see` and move PHP Links to https && wrong return types
Review
None
=> Use `@link` over `@see` and move PHP Links to https && wrong return types

.gitignore, Tests/AbstractWebApplicationTest.php, src/AbstractWebApplication.php
Ports https://github.com/joomla/joomla-cms/pull/13516 , https://github.com/joomla/joomla-cms/pull/15738 and https://github.com/joomla/joomla-cms/pull/16040 which fix cases where caching was incorrectly applied to redirect methods
This also ensure that our status codes are fully output correctly
Ensure redirects continue to work and the correct status code is used
None
=> Port fixes to the redirect method from the CMS

Tests/AbstractWebApplicationTest.php, src/AbstractWebApplication.php
Allows checking you have a valid HTTP Status code. Can be useful when doing things like checking the code associated with exceptions in the App
=> Add method to check an integer is a valid HTTP Status Code

src/AbstractCliApplication.php, src/Cli/CliInput.php, src/Cli/CliOutput.php, src/Cli/ColorProcessor.php, src/Cli/ColorStyle.php, src/Cli/Output/Processor/ColorProcessor.php, src/Cli/Output/Processor/ProcessorInterface.php, src/Cli/Output/Stdout.php, src/Cli/Output/Xml.php
Pull Request for Issue #75
Deprecates the CLI application and its supporting classes in favor of the new Console package.
=> Deprecate the CLI classes in favor of the Console package

Tests/AbstractApplicationTest.php, Tests/AbstractWebApplicationTest.php, composer.json, src/AbstractApplication.php, src/AbstractWebApplication.php, src/ApplicationEvents.php, src/Event/ApplicationEvent.php
The Framework was largely decoupled, unopinionated, and a lot of effort went into making packages independent which resulted in some basic functionality as compared to the Platform and CMS not being available.  Let's try to reverse course on this a little bit.
Basic event support is now restored to the base abstract application and the web application (as they're the only two with `execute()` methods).  Events will be triggered at four integration points:
- Before/After the `doExecute()` call
- For web applications, before/after the `render()` call
Note support for events and what the event objects are
Should events on the web application be able to possibly interrupt the workflow, somewhat similar to Symfony's Kernel events (i.e. if the before execute event sets a response, don't trigger …
=> [2.0] Event support restored

src/AbstractWebApplication.php
We're hardcoded to only send HTTP/1.1 responses right now.  This PR opens up the API to allow the version to be specified, allowing HTTP/2 responses.
With an application, call `$app->httpVersion = '1.0';` to downgrade to HTTP/1.0 as an example.
N/A
=> Allow HTTP protocol version to be defined

Tests/AbstractWebApplicationTest.php, src/AbstractWebApplication.php
When the compression of the response is delegated to Apache with mod_deflate, two headers are set during the compression:
```
Content-Encoding: gzip
Vary: Accept-Encoding
```
Vary: Accept-Encoding is important to prevent proxies, intermediate caches, or CDNs from serving compressed resource to clients that does not support compression and vice versa.
"Vary: Accept-Encoding" header specifies that caches should only be used if the incoming request matches the "Accept-Encoding" information in the cache.
When the mod_deflate is disabled in the web server, and the compression is delegated to Joomla through Global Configuration → Server → Gzip Page Compression, in this case the header "Content-Encoding: gzip" is set, but "Vary: Accept-Encoding" no, which causes the problem mentioned above on …
=> Occasional problem of corrupted html

docs/v1-to-v2-update.md, src/AbstractWebApplication.php
- Makes the `getFormToken` a concrete method again, by default calling `$this->getSession()->getToken();`
- Changes `checkToken` so that
- It also validates the token against the session
- Does not arbitrarily redirect to an `index.php` file if the session is new
Given the inherent coupling to a session for most use cases with CSRF, having these two methods internally dependent on a session being registered to the application seems perfectly fine
=> CSRF DX improvements

Tests/Controller/ContainerControllerResolverTest.php, Tests/Controller/ControllerResolverTest.php, Tests/Stubs/Controller.php, Tests/Stubs/HasArgumentsController.php, Tests/WebApplicationTest.php, composer.json, src/Controller/ContainerControllerResolver.php, src/Controller/ControllerResolver.php, src/Controller/ControllerResolverInterface.php, src/WebApplication.php
Note: Requires https://github.com/joomla-framework/router/pull/12 and CI will fail without it
There are some tools we can provide to help getting web applications deployed a little quicker, and that's what this PR provides.
Item 1 - A controller resolver.  In 1.x this really didn't make sense to need because the router was coded in a way where a controller had to map to a `Joomla\Controller\ControllerInterface` implementation, that requirement is removed in the 2.0 code and controllers can now be any kind of callable.  Based loosely on the resolver in Symfony's HttpKernel component, our implementation can support:
- Any invokable object (i.e. a Closure or a class with `__invoke`
- A standard callback array (i.e. `[ControllerInterface::class, 'execute']`
- Any declared PHP function
- A …
=> [2.0] Add a controller resolver and a concrete web application

src/AbstractWebApplication.php
Allow for SSL offloading at loadbalancer level while still letting Joomla know it is working in HTTPS mode
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/9756
This changes the way that Joomla checks if HTTPS is enabled when SSL offloading is taking place at a proxy or a loadbalancer for example.
Configure your server to add a header HTTP_X_FORWARDED_PROTO "https"
With nginx:
proxy_set_header X-Forwarded-Proto $thescheme;
None?
=> Allow SSL offloading at loadbalancer

src/AbstractApplication.php, src/ApplicationInterface.php, src/ConfigurationAwareApplicationInterface.php
When implementing the `joomla/console` package, there are two pain points in the package's design:
- Inability to extend `Symfony\Component\Console\Application` (which basically mandates we have to have our own base Application and Command classes with no ability to use the upstream classes or anything that might be compatible with `symfony/console`)
- Proxying `joomla/input` into `Symfony\Component\Console\Input\InputInterface` which in effect means there are two copies of the input data floating around (one inside `Joomla\Input\Cli` which isn't really kept in sync and the `Joomla\Console\Input\JoomlaInput` class which is a subclass of `Symfony\Component\Console\Input\ArgvInput` and is really the main input data source in this context)
This PR addresses one of those pain points, being …
=> Introduce interfaces for the application class chain
